# Generated by Django 6.0.2 on 2026-02-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
